//! Fetch the networks the engine's `nets.toml` marks `embed = true` and generate the table that
//! compiles them into this crate. The networks live in their own crate so the 150 MB of
//! weights are compiled once and cached: editing the engine never recompiles them.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;
use sha2::{Digest, Sha256};

fn main() {
    embed_networks();
    println!("cargo:rerun-if-changed=build.rs");
}

/// `nets.toml` sits at the engine's root, one level above this crate.
fn nets_toml() -> PathBuf {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .expect("nets/ has a parent")
        .join("nets.toml")
}

fn out_dir() -> PathBuf {
    PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"))
}

#[derive(Deserialize)]
struct Nets {
    default: String,
    nets: BTreeMap<String, Net>,
}

/// Where published networks live: the `nets` release of the engine's repository.
const RELEASE_URL: &str = "https://github.com/akhileshsharma99/marina/releases/download/nets";

#[derive(Deserialize)]
struct Search {
    cpuct: u32,
    fpu_reduction: u32,
    batch: u32,
}

#[derive(Deserialize)]
struct Net {
    revision: String,
    search: Search,
    model_json_sha256: String,
    model_safetensors_sha256: String,
    vectors_sha256: String,
    embed: bool,
}

/// Read `nets.toml`, make sure every embedded network's files are in `$OUT_DIR/nets/<name>/`
/// with the pinned hashes, and write `$OUT_DIR/embedded_nets.rs`. Without the `embedded`
/// feature the table is generated empty (the names are still known).
fn embed_networks() {
    let pins = nets_toml();
    println!("cargo:rerun-if-changed={}", pins.display());
    println!("cargo:rerun-if-env-changed=MARINA_NETS_DIR");
    println!("cargo:rerun-if-env-changed=MARINA_NETS_URL");
    let text = fs::read_to_string(&pins).expect("nets.toml");
    let nets: Nets = toml::from_str(&text).expect("nets.toml parses");
    assert!(
        nets.nets.contains_key(&nets.default),
        "nets.toml: default {:?} is not a listed network",
        nets.default
    );
    for (name, net) in &nets.nets {
        assert!(
            net.revision.len() == 8 && net.revision.bytes().all(|b| b.is_ascii_hexdigit()),
            "nets.toml: {name}.revision is not the 8-digit hex prefix of the weights' sha256"
        );
        assert!(
            net.model_safetensors_sha256.starts_with(&net.revision),
            "nets.toml: {name}.revision must be the first 8 digits of model_safetensors_sha256"
        );
        for (what, hash) in [
            ("model_json_sha256", &net.model_json_sha256),
            ("model_safetensors_sha256", &net.model_safetensors_sha256),
            ("vectors_sha256", &net.vectors_sha256),
        ] {
            assert!(
                hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit()),
                "nets.toml: {name}.{what} is not a 64-digit hex sha256"
            );
        }
    }
    let embedding = std::env::var_os("CARGO_FEATURE_EMBEDDED").is_some();

    let mut table = String::new();
    table.push_str("// Generated by build.rs from nets.toml. Do not edit.\n");
    table.push_str(&format!("pub const DEFAULT: &str = {:?};\n", nets.default));
    table.push_str("pub static KNOWN: &[Known] = &[\n");
    for (name, net) in &nets.nets {
        table.push_str(&format!(
            "    Known {{ name: {:?}, revision: {:?}, embedded: {}, search: SearchDefaults {{ cpuct_centi: {}, fpu_reduction_centi: {}, batch: {} }} }},\n",
            name, net.revision, net.embed, net.search.cpuct, net.search.fpu_reduction, net.search.batch
        ));
    }
    table.push_str("];\n");
    table.push_str("pub static EMBEDDED: &[Embedded] = &[\n");
    if embedding {
        for (name, net) in nets.nets.iter().filter(|(_, net)| net.embed) {
            let dir = out_dir().join("nets").join(name);
            fs::create_dir_all(&dir).expect("create nets dir");
            let json = fetch(net, name, &dir, "model.json", &net.model_json_sha256);
            let weights = fetch(
                net,
                name,
                &dir,
                "model.safetensors",
                &net.model_safetensors_sha256,
            );
            let vectors = fetch(net, name, &dir, "vectors.npz", &net.vectors_sha256);
            table.push_str(&format!(
                "    Embedded {{ name: {:?}, revision: {:?}, model_json: include_str!({:?}), \
                 model_safetensors: include_bytes!({:?}), vectors: {:?}, vectors_sha256: {:?} }},\n",
                name,
                net.revision,
                json.display().to_string(),
                weights.display().to_string(),
                vectors.display().to_string(),
                net.vectors_sha256
            ));
        }
    }
    table.push_str("];\n");
    table.push_str(&format!(
        "/// Where the networks' release assets live (`<name>-<revision>.<file>`).\npub const RELEASE_URL: &str = {RELEASE_URL:?};\n"
    ));
    fs::write(out_dir().join("embedded_nets.rs"), table).expect("write embedded_nets.rs");
}

/// Ensure `dir/file` exists with the expected sha256: keep it if it already matches, else
/// copy it from `$MARINA_NETS_DIR/<name>/file` when that is set, else download the
/// `<name>-<revision>.<file>` asset with curl, from `$MARINA_NETS_URL` when that is set (a
/// mirror or a staging release) and from the `nets` release otherwise. A hash mismatch
/// from any source fails the build.
fn fetch(net: &Net, name: &str, dir: &Path, file: &str, expected: &str) -> PathBuf {
    let target = dir.join(file);
    if matches(&target, expected) {
        return target;
    }
    let partial = dir.join(format!("{file}.partial"));
    let _ = fs::remove_file(&partial);
    if let Some(local) = std::env::var_os("MARINA_NETS_DIR") {
        let source = PathBuf::from(local).join(name).join(file);
        fs::copy(&source, &partial).unwrap_or_else(|error| {
            panic!(
                "cannot copy {} for network {name}: {error}",
                source.display()
            )
        });
    } else {
        let base = std::env::var("MARINA_NETS_URL")
            .ok()
            .filter(|u| !u.trim().is_empty())
            .map(|u| u.trim_end_matches('/').to_string())
            .unwrap_or_else(|| RELEASE_URL.to_string());
        let url = format!("{base}/{name}-{}.{file}", net.revision);
        let status = Command::new("curl")
            .args([
                "--fail",
                "--silent",
                "--show-error",
                "--location",
                "--retry",
                "3",
            ])
            .arg("--output")
            .arg(&partial)
            .arg(&url)
            .status()
            .unwrap_or_else(|error| panic!("cannot run curl to fetch {url}: {error}"));
        assert!(
            status.success(),
            "downloading {url} failed; set MARINA_NETS_DIR to a directory holding \
             <name>/model.json and <name>/model.safetensors to build offline, or build with \
             --no-default-features to leave the networks out"
        );
    }
    let actual = sha256_hex(&partial);
    assert!(
        actual.eq_ignore_ascii_case(expected),
        "network {name}: {file} fetched from {} has sha256 {actual}, nets.toml pins {expected}",
        std::env::var_os("MARINA_NETS_DIR")
            .map(|_| "MARINA_NETS_DIR".to_string())
            .unwrap_or_else(|| "the nets release".to_string())
    );
    fs::rename(&partial, &target).expect("rename fetched network file");
    target
}

fn matches(path: &Path, expected: &str) -> bool {
    path.exists() && sha256_hex(path).eq_ignore_ascii_case(expected)
}

fn sha256_hex(path: &Path) -> String {
    let mut file =
        fs::File::open(path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    let mut hasher = Sha256::new();
    std::io::copy(&mut file, &mut hasher).expect("hash file");
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}
